# Generated by Django 5.2.2 on 2026-09-14 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ipblockrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=20)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('risk_type', models.CharField(choices=[('blocked_ip', '黑名单 IP'), ('auth_failed', '认证失败'), ('permission_denied', '权限拒绝'), ('rate_limited', '限流'), ('server_error', '服务异常')], max_length=50)),
                ('count', models.PositiveIntegerField(default=1)),
                ('window_seconds', models.PositiveIntegerField(default=60)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_risk_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
