# Generated by Django 5.2.2 on 2026-09-18 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('general', '通用申请'), ('payment', '打款申请'), ('ai_review', 'AI 人工审核')], default='general', max_length=50, verbose_name='申请类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='金额')),
                ('business_data', models.JSONField(blank=True, default=dict, verbose_name='业务数据')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已取消')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_workflow_requests', to=settings.AUTH_USER_MODEL, verbose_name='当前审批人')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('submit', '提交'), ('approve', '通过'), ('reject', '驳回'), ('cancel', '取消')], max_length=30, verbose_name='动作')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, default='', max_length=20, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, default='', verbose_name='备注')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='workflows.workflowrequest', verbose_name='工作流申请')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
