# Generated by Django 5.2.2 on 2026-09-18 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('pay_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信')], max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('user_paid', '用户已支付'), ('confirmed', '已确认到账'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='支付状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='用户支付时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认到账时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='workflows.workflowrequest', verbose_name='关联工作流')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
