# Generated by Django 5.2.2 on 2026-09-18 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowrequest_second_approver_workflowtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='模板编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='workflowrequest',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_workflow_requests', to=settings.AUTH_USER_MODEL, verbose_name='一级审批人'),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_requests', to='workflows.workflowtemplate', verbose_name='流程模板'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('node_order', models.PositiveIntegerField(verbose_name='节点顺序')),
                ('approver_field', models.CharField(choices=[('current_approver', '一级审批人'), ('second_approver', '二级审批人')], max_length=50, verbose_name='审批人字段')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflowtemplate', verbose_name='流程模板')),
            ],
            options={
                'ordering': ['node_order', 'id'],
                'unique_together': {('template', 'node_order')},
            },
        ),
    ]
