# Generated by Django 5.2.2 on 2026-09-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflowtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplatenode',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='最低适用金额'),
        ),
    ]
