# Generated by Django 5.2.15 on 2026-06-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicalllog',
            name='response',
            field=models.TextField(blank=True, default='', verbose_name='AI返回'),
            preserve_default=False,
        ),
    ]
