# Generated by Django 5.2.15 on 2026-07-06 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_log', '0002_alter_aicalllog_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicalllog',
            options={'ordering': ['-call_time'], 'verbose_name': 'AI调用日志', 'verbose_name_plural': 'AI调用日志'},
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='aicalllog',
            name='response',
            field=models.TextField(blank=True, default='', verbose_name='AI返回'),
        ),
    ]
