# Generated by Django 5.2.2 on 2026-07-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_log', '0003_alter_aicalllog_options_aicalllog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='completion_tokens',
            field=models.IntegerField(default=0, verbose_name='输出Token数'),
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='cost',
            field=models.FloatField(default=0, verbose_name='费用（元）'),
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='prompt_tokens',
            field=models.IntegerField(default=0, verbose_name='输入Token数'),
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='total_tokens',
            field=models.IntegerField(default=0, verbose_name='总Token数'),
        ),
    ]
