# Generated by Django 5.2.2 on 2026-07-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_log', '0004_aicalllog_completion_tokens_aicalllog_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='conversation_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='会话ID'),
        ),
    ]
