# Generated by Django 5.2.2 on 2026-07-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_log', '0005_aicalllog_conversation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='模板名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='模板描述')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('variables', models.JSONField(default=list, verbose_name='变量列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'prompt模板',
                'verbose_name_plural': 'prompt模板',
                'ordering': ['name'],
            },
        ),
    ]
