# Generated by Django 5.2.2 on 2026-09-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_log', '0009_knowledgedocument_knowledgechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='链路追踪ID'),
        ),
    ]
