# Generated by Django 5.2.2 on 2026-09-01 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_log', '0010_aicalllog_trace_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTraceStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64, verbose_name='链路跟踪ID')),
                ('conversation_id', models.CharField(blank=True, default='', max_length=64, verbose_name='会话ID')),
                ('step', models.CharField(max_length=50, verbose_name='步骤')),
                ('query', models.TextField(blank=True, default='', verbose_name='用户问题')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='步骤详情')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('duration', models.FloatField(default=0.0, verbose_name='步骤耗时')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'RAG步骤追踪日志',
                'verbose_name_plural': 'RAG步骤追踪日志',
                'ordering': ['created_at'],
            },
        ),
    ]
