# Generated by Django 5.2.2 on 2026-09-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_log', '0011_ragtracelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitracesteplog',
            options={'ordering': ['created_at'], 'verbose_name': 'AI请求步骤追踪日志', 'verbose_name_plural': 'AI请求步骤追踪日志'},
        ),
    ]
