# Generated by Django 5.2.2 on 2026-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_log', '0013_fix_aitracesteplog_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitracesteplog',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Celery任务ID'),
        ),
    ]
