# Generated by Django 5.2.2 on 2026-09-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_log', '0014_aitracesteplog_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitracesteplog',
            name='task_id',
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Celery任务ID'),
        ),
    ]
