# Generated by Django 5.2.2 on 2026-09-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_log', '0015_remove_aitracesteplog_task_id_aicalllog_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='embedding',
            field=models.JSONField(blank=True, default=list, verbose_name='向量表示'),
        ),
    ]
