# Generated by Django 5.2.2 on 2026-10-10 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material_type', models.CharField(default='video', max_length=20)),
                ('storage_type', models.CharField(default='local', max_length=20)),
                ('local_path', models.CharField(blank=True, default='', max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='novel_video/materials/')),
                ('style', models.CharField(db_index=True, max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('duration', models.FloatField(default=0)),
                ('aspect_ratio', models.CharField(blank=True, default='9:16', max_length=20)),
                ('is_shared', models.BooleanField(default=False)),
                ('commercial_use', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('novel_text', models.TextField()),
                ('style', models.CharField(db_index=True, max_length=50)),
                ('target_duration', models.PositiveIntegerField(default=60)),
                ('voice_mode', models.CharField(default='existing_audio', max_length=30)),
                ('audio_path', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('script', models.JSONField(blank=True, default=dict)),
                ('output_dir', models.CharField(blank=True, default='', max_length=500)),
                ('final_path', models.CharField(blank=True, default='', max_length=500)),
                ('cover_path', models.CharField(blank=True, default='', max_length=500)),
                ('subtitle_path', models.CharField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
