# Generated by Django 5.2.2 on 2026-10-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojob',
            name='audio_path',
        ),
        migrations.RemoveField(
            model_name='videojob',
            name='voice_mode',
        ),
        migrations.AddField(
            model_name='videojob',
            name='background_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_jobs', to='novel_video.materialasset'),
        ),
        migrations.AddField(
            model_name='videojob',
            name='bgm_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgm_jobs', to='novel_video.materialasset'),
        ),
        migrations.AddField(
            model_name='videojob',
            name='bgm_loop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videojob',
            name='bgm_volume',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='videojob',
            name='font_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='videojob',
            name='font_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='videojob',
            name='font_size',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name='videojob',
            name='name_replacements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videojob',
            name='opening_audio_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_audio_jobs', to='novel_video.materialasset'),
        ),
        migrations.AddField(
            model_name='videojob',
            name='opening_duration',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='videojob',
            name='opening_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videojob',
            name='render_mode',
            field=models.CharField(default='scrolling_text', max_length=30),
        ),
        migrations.AddField(
            model_name='videojob',
            name='scrolling_end_y',
            field=models.IntegerField(default=-1600),
        ),
        migrations.AddField(
            model_name='videojob',
            name='scrolling_speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='videojob',
            name='scrolling_start_y',
            field=models.IntegerField(default=1600),
        ),
        migrations.AddField(
            model_name='videojob',
            name='sentence_position',
            field=models.CharField(default='center', max_length=50),
        ),
        migrations.AddField(
            model_name='videojob',
            name='split_punctuation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videojob',
            name='text_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='materialasset',
            name='style',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='style',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
