# Generated by Django 5.2.2 on 2026-10-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_video', '0002_remove_videojob_audio_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='target_duration',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
