# Generated by Django 5.2.2 on 2026-10-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_video', '0003_alter_videojob_target_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialasset',
            name='duration',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
